name: CaseOpening
authors:
  - byBackfish
version: 1.0.1
main: de.bybackfish.caseopening.main.CaseOpening
description: CaseOpening Plugin
database: false
commands:
  test:
    description: Just an Dev-Debug Command
    usage: /test
